# backend:
#   name: git-gateway
#   branch: master # Branch to update (optional; defaults to master)

backend:
  name: github
  repo: aidanbrown87/one_day_away
  branch: netlify-test

media_folder: static/assets
public_folder: assets

# This line should *not* be indented
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }